### ISSUE TITLE
Creating Meeting Notes Now Does Not Work

### ISSUE THREAD

**Issue by AlecKC** [acm-uiuc/groot-desktop-frontend#108]
Attached images of issue.

![ButtonClicked](https://cloud.githubusercontent.com/assets/8867698/24589545/e167b1cc-17a1-11e7-8b3d-8915479a963b.PNG)
![Problem](https://cloud.githubusercontent.com/assets/8867698/24589548/eef33d20-17a1-11e7-8630-3c95c8e89242.PNG)

**Comment by wchill** [comment]
@aashishkapur 
Probably related to the wiki migration; this is not actually a Groot issue though.
