### ISSUE TITLE
Bad layout for social media buttons on mobile on homepage

### ISSUE THREAD

**Issue by lalicari** [acm-uiuc/groot-desktop-frontend#110]

**Comment by narendasan** [comment]
@lalicari thanks for putting in the issue. @redsn0w422 can you address this?

**Comment by narendasan** [comment]
![img_2098](https://cloud.githubusercontent.com/assets/1790613/24600728/c1b2300a-180a-11e7-9e32-e8171830b57c.PNG)

**Comment by redsn0w422** [comment]
@narendasan, can you mock up what you'd like it to look like on mobile? I can fix it, but it doesn't look very good on iPhone 5:

![image](https://cloud.githubusercontent.com/assets/3170794/24619095/99961cea-185e-11e7-9628-8d40147ef794.png)

**Comment by narendasan** [comment]
Either scale down the font size (there is a media tag section for mobile) or make a menu like the nav bar

**Comment by narendasan** [comment]
@redsn0w422 do you have a working build (minus the font scaling)?

**Comment by redsn0w422** [comment]
@narendasan 
![image](https://cloud.githubusercontent.com/assets/3170794/24708559/d4b7bb9c-19dc-11e7-83fe-a8e3eede3d71.png)

**Comment by narendasan** [comment]
Cool, PR?

**Comment by redsn0w422** [comment]
#114

**Comment by lalicari** [comment]
Has this been pushed live yet? I’m not seeing the fix.

Thanks,
Laura

**Comment by narendasan** [comment]
The PR is in review, most likely deployed on monday when we deploy the new environment

**Comment by lalicari** [comment]
Cool, thanks for addressing the issues so quickly. :)
