### ISSUE TITLE
acm.illinois.edu is down

### ISSUE THREAD

**Issue by lalicari** [acm-uiuc/groot-desktop-frontend#115]
Was trying to see if the social media button fix was pushed live, but now the site is down. If there's maintenance going on, please ignore this.

Getting ERR_CONNECTION_FAILED on mobile (Chrome) , get this on desktop (also Chrome):

It works!

This is the default web page for this server.

The web server software is running but no content has been added, yet.

**Comment by aashishkapur** [comment]
Thanks for reporting this, and we're back up now.
