### ISSUE TITLE
Incorrect display times for events pulled from Facebook

### ISSUE THREAD

**Issue by rauhul** [acm-uiuc/groot-desktop-frontend#136]
The times for events created in Facebook are incorrect (assuming timezone issue)

<img width="317" alt="screen shot 2017-09-06 at 11 01 57 am" src="https://user-images.githubusercontent.com/9739930/30122043-dff0aef8-92f2-11e7-9649-3e6dfb5e2dd5.png">

**Comment by bcongdon** [comment]
Fixed. I suspect it was because the changes that were merged a couple days ago to fix this issue were never deployed.
