### ISSUE TITLE
Consider using Slackin for easy slack onboarding

### ISSUE THREAD

**Issue by pranaygp** [acm-uiuc/groot-desktop-frontend#146]
Since we're trying to make this transition to using slack, would it make sense to deploy slackin and have slack.acm.illinois.edu redirect to our slackin deployment? This would let people use the slack with their personal email accounts.

https://github.com/rauchg/slackin

**Comment by narendasan** [comment]
Anyone with a @illinois.edu email can already create an account without needing an invite. Is there a reason we should be letting people use another email? Seems harder to police

**Comment by pranaygp** [comment]
While trying to send you a screenshot to explain why, I just realised that slack lets you sign in with different email addresses to different teams and have them all appear on this list:

![image](https://user-images.githubusercontent.com/1797812/30776194-d0062644-a067-11e7-8182-b457b42c323c.png)


I suppose it doesn't matter then. My issue was having to switch between slack instances for "things logged into with illinois.edu" and "things logged into with personal email.
