### ISSUE TITLE
New RP description 

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/groot-desktop-frontend#53]
We need a new description for the RP page

**Comment by Salil999** [comment]
Pulled from the 2016 page.

> Reflections | Projections is a tech conference organized and run by students at the University of Illinois at Urbana-Champaign.
We draw students, speakers, and companies from around the world. Join us to listen to tech talks from across the industry, to participate in an Artificial Intelligence programming competition in Mechmania, to solve puzzles throughout the conference during PuzzleBang!, and to attend our job and startup fairs.
The conference is free and open to anyone regardless of age, major, job, or affiliation with the University of Illinois. So come join a discussion led by some of the brightest minds in the business about the bleeding edge of the tech industry!

**Comment by ShivaliPatel2** [comment]
business and academia

**Comment by ShivaliPatel2** [comment]
i think somehow we should mention how it was founded and conitnually run by students for over 20 years, i think that makes a good impression

**Comment by theishshah** [comment]
Reflections | Projections is a technology conference founded and operated by students at the University of Illinois. ACM@UIUC started the conference over 20 years ago in 1995.

We strive to cater to both business and academia by providing a forum to share and learn about the happenings in the world of tech. We have tech talks from across the industry, micro-talks and workshops, and a video game artificial intelligence competition in Mechmania.

To top it all off, the conference is completely free for anyone to attend, regardless of age, major, career, or affiliation with UIUC. Come join an amazing conference led by some of the best and brightest from around the nation.

**Comment by aashishkapur** [comment]
We also need to change the RP logo on the page to
![this one.](https://cloud.githubusercontent.com/assets/2781220/23638097/213b1954-02a5-11e7-8aec-6b0930a3027d.png)

**Comment by ShivaliPatel2** [comment]
Reflections | Projections, founded in 1995, is a technology conference operated by students in ACM@UIUC. Striving to cater to our community of students, alumni, and professionals, we provide a forum to share and learn about current advancements in computer science and its applications. We have tech talks from across the industry and academia, workshops and puzzle-solving events for attendees, and Mechmania, our annual artificial intelligence programming competition. The entire conference is completely free for anyone to attend, regardless of age, major, or affiliation with UIUC.
This year, Reflections | Projections will occur September 29th - October 1st, immediately following ACM Career Week, which features a job fair, a startup fair and company visits.
