### ISSUE TITLE
left alignment on homepage

### ISSUE THREAD

**Issue by maxwellyoungio** [acm-uiuc/groot-desktop-frontend#54]
this 
<img width="1076" alt="wrong" src="https://cloud.githubusercontent.com/assets/13542181/22258807/9f1154b2-e228-11e6-97e0-9296ab0e558f.png">

should be this 
<img width="1113" alt="right" src="https://cloud.githubusercontent.com/assets/13542181/22258845/b23d63dc-e228-11e6-9b1c-4188c6542290.png">

possible solution
<img width="329" alt="code" src="https://cloud.githubusercontent.com/assets/13542181/22258908/ee9e5dd6-e228-11e6-94e4-fa21dbb85abc.png">

**Comment by narendasan** [comment]
Can you submit a PR for review?

**Comment by narendasan** [comment]
Also be aware that the rules must work for the whole range of display widths

**Comment by maxwellyoungio** [comment]
sure, which one has the main.css file? I can't locate it but I'm new to github so I might just be looking in the wrong place

**Comment by narendasan** [comment]
The code is in less check public/less/partials/home.less

**Comment by tyler-thetyrant** [comment]
Fixed with #59
