### ISSUE TITLE
Better 404 Page

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-desktop-frontend#56]
Something like: https://github.com/acm-uiuc/liquid/blob/master/liquid/templates/404.html

**Comment by sameetandpotatoes** [comment]
Closing as this is now in production

**Comment by narendasan** [comment]
So found this, perhaps worth bringing back the old 404 to keep it alive?
https://motherboard.vice.com/en_us/article/probably-the-most-uncanny-404-page
