### ISSUE TITLE
Controller/services nesting is redundant

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/groot-desktop-frontend#66]
remove either the controller folder or the services folder, they are redundant

**Comment by sameetandpotatoes** [comment]
I agree - I was going a little overboard on organization. I'll probably keep the controllers folder.

**Comment by bcongdon** [comment]
This is a bit of a separate issue, but it might be a good idea to group the `*.ejs` files in `views` by service.

(i.e. `views/recruiters` contains all the recruiter view templates, etc)

**Comment by sameetandpotatoes** [comment]
Yeah I agree actually, would be a good idea to separate this - with that change, maybe `controllers` can be renamed to `app`, and then have `services` (potentially renamed to controllers, to be a little more MVC maybe) along with `views`

**Comment by narendasan** [comment]
Also have the path to the ejs file reflect the URL on the site

**Comment by sameetandpotatoes** [comment]
I'll do this after the users service and credits service stuff gets merged.

**Comment by bcongdon** [comment]
User/credits stuff is merged, I think it would be a good time to make this change.

**Comment by sameetandpotatoes** [comment]
Closing as this was merged.
