### ISSUE TITLE
What is 'hello_world.ejs'?

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-desktop-frontend#77]
I'm assuming [this](https://github.com/acm-uiuc/groot-desktop-frontend/blob/master/app/views/_partials/hello_world.ejs) can be removed?

**Comment by tyler-thetyrant** [comment]
I think this is the message animation that plays when you visit the website.

**Comment by bcongdon** [comment]
Ah, ok. My real complaint is more so the `console.log` that it does.

**Comment by narendasan** [comment]
yeah I think the console log link can be removed

**Comment by bcongdon** [comment]
Sliding this into #76
