### ISSUE TITLE
Sponsor updates

### ISSUE THREAD

**Issue by tyler-thetyrant** [acm-uiuc/groot-desktop-frontend#82]
- Add Nvidia as a silver sponsor

- Add top sponsors from RP 2016 and HackIllinois 2017

**Comment by narendasan** [comment]
any progress here?

**Comment by traugertyson** [comment]
Yes, I added Nvidia as silver sponser locally; still trying to figure out what I'm doing with git. Sorry for the delay.
However, I am a bit confused by the second point, where would they be added and what would be considered a top sponser?

**Comment by narendasan** [comment]
@tyler-thetyrant ^

**Comment by aashishkapur** [comment]
@traugertyson Do you need help with git?

**Comment by traugertyson** [comment]
@aashishkapur I think I got it now, thanks though! I had to change the remote from acm-uiuc to my fork

**Comment by tyler-thetyrant** [comment]
Hey @traugertyson 
We would like Fulcrum, IMO and MSFT's logos for HackIllinosi 2017 top sponsors
For RP 2016's top sponsors, let's add RetailMeNot and Palantir.
Assets can be found here: https://github.com/HackIllinois/site-2017/tree/master/src/assets/img/home/sponsors  and https://github.com/ReflectionsProjections/rp2016/tree/master/jobfair/assets/logos

They can be listed the same way each sponsorship tiers can be listed. Name each category as `HackIllinois 2017 Top Sponsors` and `Reflections|Projections 2016 Top sponsors`

If you have any questions, hop on our gitter chat.
