### ISSUE TITLE
Intranet graceful fail

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-desktop-frontend#83]
Currently, if merch service isn't running, hitting `/intranet` returns an internal server error.

Would be good to selectively not render the merch side panel, or handle the error in a more graceful way.

**Comment by aashishkapur** [comment]
The issue is [this line](https://github.com/acm-uiuc/groot-desktop-frontend/blob/master/server.js#L162), causing the intranet route not to return the view and return an error instead.

**Comment by wchill** [comment]
Also it should be a 503 not 500, but that's a minor point.

**Comment by sameetandpotatoes** [comment]
So do we handle this by returning "N/A" for pin and balance?

**Comment by aashishkapur** [comment]
I think the best option would be to change the template to replace what's there with the pin/balance and say something like "Credits are currently unavailable, check back later(or contact admin)".

**Comment by sameetandpotatoes** [comment]
This should be fixed, thanks to @tiopi's merge. @bcongdon Can you verify this so that this issue can be closed?

**Comment by bcongdon** [comment]
Yeah, this works. Ideally it would have some type of "unavailable" value, but we can close this for now.
