### ISSUE TITLE
Increase padding between intranet services 

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/groot-desktop-frontend#84]
its getting a bit crowded on the intranet, we should increase the padding a bit

**Comment by bcongdon** [comment]
As in, padding between the cards on the intranet dashboard?

**Comment by narendasan** [comment]
Yeah

**Comment by bcongdon** [comment]
Fixed in https://github.com/acm-uiuc/groot-desktop-frontend/commit/bae2e759784651517e5217c0ec8636371ec6db8d
