### ISSUE TITLE
Switch social media logos to Font Awesome

### ISSUE THREAD

**Issue by redsn0w422** [acm-uiuc/groot-desktop-frontend#87]
Currently using SVGs

**Comment by narendasan** [comment]
@redsn0w422 want to put in a PR?

**Comment by redsn0w422** [comment]
@narendasan will do

**Comment by narendasan** [comment]
cool, Hop on the gitter if you have questions

**Comment by narendasan** [comment]
@redsn0w422  any progress here?

**Comment by redsn0w422** [comment]
Haven't figured out the CSS yet (been out of town).

**Comment by redsn0w422** [comment]
@narendasan #87
