### ISSUE TITLE
Credits exchange rate

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/groot-desktop-frontend#89]
credits should ideally not require decimals so we should multiply values by 100 when showing them on UIs.
So effectively $1 = 100ℂ

**Comment by bcongdon** [comment]
I'd suggest that if we do this, we change credits internally to be integers.

**Comment by narendasan** [comment]
Probably better imo, floats suck

**Comment by narendasan** [comment]
cc: @rauhul

**Comment by rauhul** [comment]
Sounds good to me!

**Comment by narendasan** [comment]
Could we get this implemented before merch goes online?

**Comment by rauhul** [comment]
@narendasan @bcongdon we are trying to bring Merch live before SAIL so this is a high priority

**Comment by bcongdon** [comment]
Alright, this change has been made:
https://github.com/acm-uiuc/groot-credits-service/pull/8
https://github.com/acm-uiuc/groot-desktop-frontend/pull/113
https://github.com/acm-uiuc/groot-gigs-service/pull/4

**Comment by narendasan** [comment]
do changes need to be made to merch service and the ios app?

**Comment by bcongdon** [comment]
I'd imagine so, though I'm not sure how those projects work internally

**Comment by narendasan** [comment]
@sameetandpotatoes @rauhul ^

**Comment by sameetandpotatoes** [comment]
Nope, no changes to merch. balance is fetched from credits and stored in a global variable per user model.

**Comment by narendasan** [comment]
what about storing the cost for each item?

**Comment by sameetandpotatoes** [comment]
Prices are already integers in merch.
